project_name: prometheus2mqtt
before:
  hooks:
    - go mod tidy
builds:
  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/krzysztof-gzocha/prometheus2mqtt/config.Version={{.Version}}

  - id: rasp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarm:
      - 7
      - 6
    goarch:
      - arm64
    ldflags:
      - -s -w -X github.com/krzysztof-gzocha/prometheus2mqtt/config.Version={{.Version}}

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
      arm: rasp
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - id: linux
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    image_templates:
      - "krzysztofgzocha/prometheus2mqtt:{{ .Tag }}-amd64"
    extra_files: # no idea WTF I need to add this..
      - go.mod
      - go.sum
      - main.go
      - config/
      - prometheus/
      - publisher/
      - ticker/
      - vendor/
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=VERSION={{.Version}}"

#  - id: rasp
#    goos: linux
#    goarch: arm64
#    goarm: 7
#    dockerfile: Dockerfile
#    image_templates:
#      - "krzysztofgzocha/prometheus2mqtt:{{ .Tag }}-arm64"
#    extra_files: # no idea WTF I need to add this..
#      - go.mod
#      - go.sum
#      - main.go
#      - config/
#      - prometheus/
#      - ticker/
#      - vendor/
#    build_flag_templates:
#      - "--platform=linux/arm64/v8"
#
#docker_manifests:
#  - name_template: "krzysztofgzocha/prometheus2mqtt:{{ .Tag }}"
#    image_templates:
#      - "krzysztofgzocha/prometheus2mqtt:{{ .Tag }}-arm64"
#      - "krzysztofgzocha/prometheus2mqtt:{{ .Tag }}-amd64"
release:
  github:
    owner: krzysztof-gzocha
    name: prometheus2mqtt
