project_name: prometheus2mqtt
before:
  hooks:
    - go mod tidy
builds:
  - id: p2m
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: p2m_rasp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarm:
      - 7
      - 6
    goarch:
      - arm
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
