project_name: prometheus2mqtt
before:
  hooks:
    - go mod tidy
builds:
  - id: p2m
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: p2m_rasp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarm:
      - 7
      - 6
    goarch:
      - arm
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
      arm: rasp
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - id: rasp
    goos: linux
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile
    image_templates:
      - "krzysztofgzocha/prometheus2mqtt:latest-arm"
      - "krzysztofgzocha/prometheus2mqtt:{{ .Tag }}-arm"
    extra_files: # no idea WTF I need to add this..
      - go.mod
      - go.sum
      - main.go
      - config/
      - prometheus/
      - ticker/
      - vendor/
release:
  github:
    owner: krzysztofgzocha
    name: prometheus2mqtt
